import { createFileRoute, notFound } from "@tanstack/react-router";
import { Check, Fuel, Gauge, ShieldCheck, Star, Users } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { cars } from "@/lib/cars";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/cars/$carId")({ loader: ({ params }) => { const car = cars.find(c=>c.id===params.carId); if(!car) throw notFound(); return car; }, head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.name} Rental — SmartRide` : "Car Not Found — SmartRide" },{ name: "description", content: loaderData ? `Book the ${loaderData.name} from $${loaderData.price} per day.` : "This car is unavailable." },{ property: "og:title", content: loaderData ? `${loaderData.name} — SmartRide` : "Car Not Found — SmartRide" },{ property: "og:description", content: loaderData ? `Reserve this ${loaderData.category} with SmartRide.` : "This car is unavailable." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: CarDetails });

function CarDetails(){ const car=Route.useLoaderData(); const [booked,setBooked]=useState(false); function book(e:FormEvent){e.preventDefault();setBooked(true);toast.success("Your car is reserved!");}
return <><SiteHeader/><main className="bg-background"><section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 lg:grid-cols-[1.35fr_.65fr] lg:px-8"><div><div className="overflow-hidden rounded-2xl bg-muted"><img src={car.image} alt={car.name} width={1000} height={650} className="aspect-[16/10] w-full object-cover"/></div><div className="mt-4 grid grid-cols-3 gap-3">{[car.image,car.image,car.image].map((image,i)=><button key={i} className="overflow-hidden rounded-xl border-2 border-transparent first:border-accent"><img src={image} alt={`${car.name} view ${i+1}`} className="aspect-[16/10] object-cover"/></button>)}</div><div className="mt-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-secondary/25 px-3 py-1 text-xs font-bold">{car.category}</span><h1 className="mt-3 text-4xl font-extrabold">{car.name}</h1><p className="mt-2 flex items-center gap-1 text-muted-foreground"><Star className="size-5 fill-highlight text-highlight"/> {car.rating} ({car.reviews} verified reviews)</p></div><p className="font-display text-3xl font-bold text-accent">${car.price}<span className="font-sans text-sm text-muted-foreground">/day</span></p></div><div className="mt-8 grid grid-cols-2 gap-4 rounded-2xl bg-muted p-6 sm:grid-cols-4"><div className="flex items-center gap-2 text-sm font-semibold"><Users className="size-5 text-accent"/>{car.seats} seats</div><div className="flex items-center gap-2 text-sm font-semibold"><Gauge className="size-5 text-accent"/>{car.transmission}</div><div className="flex items-center gap-2 text-sm font-semibold"><Fuel className="size-5 text-accent"/>{car.fuel}</div><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="size-5 text-accent"/>Protection</div></div><h2 className="mt-10 text-2xl font-bold">Made for memorable miles</h2><p className="mt-3 leading-7 text-muted-foreground">Comfortable, refined, and impeccably maintained. This SmartRide favorite blends everyday ease with the confidence to go farther.</p><h2 className="mt-10 text-2xl font-bold">Renter reviews</h2><div className="mt-4 rounded-2xl border border-border p-6"><div className="flex items-center gap-1 text-highlight">★★★★★</div><p className="mt-3 leading-7">“Easy pickup, spotless car, and exactly the price shown. The entire experience felt refreshingly simple.”</p><p className="mt-3 text-sm font-bold">Maya R. · Verified renter</p></div></div></div>
<aside><form onSubmit={book} className="sticky top-24 rounded-2xl border border-border bg-card p-6 shadow-xl"><h2 className="text-xl font-bold">Reserve this car</h2><p className="mt-1 text-sm text-muted-foreground">Free cancellation on eligible bookings.</p><div className="mt-6 space-y-4"><div><Label htmlFor="pickup-location">Pickup location</Label><Input id="pickup-location" required placeholder="City or airport" className="mt-2 h-11"/></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="from">From</Label><Input id="from" required type="date" className="mt-2 h-11"/></div><div><Label htmlFor="until">Until</Label><Input id="until" required type="date" className="mt-2 h-11"/></div></div><div className="flex items-center justify-between border-y border-border py-4"><span className="text-sm text-muted-foreground">Estimated total</span><span className="font-display text-xl font-bold">${car.price*3}</span></div><Button type="submit" variant="cta" size="lg" className="w-full">{booked?<><Check/> Reserved</>:"Book now"}</Button><p className="text-center text-xs text-muted-foreground">You won't be charged yet</p></div></form></aside></section></main><SiteFooter/></>}