/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CarsCarIdRouteImport } from './routes/cars.$carId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => CarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cars' | '/cars/$carId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars' | '/cars/$carId'
  id: '__root__' | '/' | '/cars' | '/cars/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRoute: typeof CarsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof CarsRoute
    }
  }
}

interface CarsRouteChildren {
  CarsCarIdRoute: typeof CarsCarIdRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsCarIdRoute: CarsCarIdRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRoute: CarsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
